services:
  bonsite:
    build:
      context: ./bonsite
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "3000:3000"

  database:
    build: ./database
    dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
